MyProject\MainBundle\Entity\Articles:
  type: entity
  table: articles
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
      unique: true
    text:
        type: text
    created_at:
          type: datetime
    updated_at:
          type: datetime
          nullable: true
lifecycleCallbacks:
    prePersist: [ setCreatedAtValue ]
    preUpdate: [ setUpdatedAtValue ]
