MyProject\MainBundle\Entity\Images:
  type: entity
  table: images
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
      unique: true
    desctiption:
      type: string
      length: 255
  manyToOne:
    product:
      targetEntity: Products
      inversedBy: images
      joinColumn:
        name: product_id
        referencedColumnName: id
  
