MyProject\MainBundle\Entity\User:
  type: entity
  table: users
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
      unique: true
    password:
      type: string
      length: 255
    email:
      type: string
      length: 255
