MyProjectMainBundle_homepage:
    pattern:  /
    defaults: { _controller: MyProjectMainBundle:Default:index}
MyProjectMainBundle_contacts:
    pattern:  /contacts
    defaults: { _controller: MyProjectMainBundle:Default:contacts }

MyProjectMainBundle_category:
    pattern:  /{slug}
    defaults: { _controller: MyProjectMainBundle:Default:category, slug: null }
    
MyProjectMainBundle_admin_products_view:
    pattern:  /admin/products
    defaults: { _controller: MyProjectMainBundle:News:ViewId }
    
MyProjectMainBundle_admin_category_view:
    pattern:  /admin/category
    defaults: { _controller: MyProjectMainBundle:CategoryAdmin_new:ViewId }
