services:
    myproject.mian.admin.category:
        class: MyProject\MainBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: main, label: Category }
        arguments: [null, MyProject\MainBundle\Entity\Category, MyProjectMainBundle:CategoryAdmin]

    myproject.mian.admin.products:
             class: MyProject\MainBundle\Admin\ProductsAdmin
             tags:
                 - { name: sonata.admin, manager_type: orm, group: main, label: Products }
             arguments: [null, MyProject\MainBundle\Entity\Products, MyProjectMainBundle:ProductsAdmin]