<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\MediaBundle\Entity;

use Sonata\MediaBundle\Entity\BaseMedia as BaseMedia;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Media extends BaseMedia
{
    /**
     * @var integer $id
     */
    protected $id;
 /**
     * @var integer $product_id
     */
    protected $product_id;
    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }
     /**
     * Set product_id
     *
     * @param \MyProject\MainBundle\Entity\Products $product_id
     */ 
    public function setProductId(\MyProject\MainBundle\Entity\Products $product_id)
    {
       
        $this->product_id = $product_id;
    }
    /**
     * Get product_id
     *
     * @return \MyProject\MainBundle\Entity\Products
     */
    public function getProductId()
    {

        return $this->product_id;
    }
    
}